spring.application.name=APIGateway
server.port=9000

# =========================
# Eureka
# =========================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# =========================
# Staff Management
# =========================
spring.cloud.gateway.server.webflux.routes[0].id=StaffManagement
spring.cloud.gateway.server.webflux.routes[0].uri=lb://StaffManagement
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/staff/**

# =========================
# Patient Management
# =========================
spring.cloud.gateway.server.webflux.routes[1].id=PatientManagement
spring.cloud.gateway.server.webflux.routes[1].uri=lb://PatientManagement
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/patient/**

# =========================
# Bed Management
# =========================
spring.cloud.gateway.server.webflux.routes[2].id=BedManagement
spring.cloud.gateway.server.webflux.routes[2].uri=lb://BedManagement
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/bed/**

# =========================
# Room Management
# =========================
spring.cloud.gateway.server.webflux.routes[3].id=RoomManagement
spring.cloud.gateway.server.webflux.routes[3].uri=lb://BedManagement
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/room/**

# =========================
# Bed Assignment
# =========================
spring.cloud.gateway.server.webflux.routes[4].id=BedAssignment
spring.cloud.gateway.server.webflux.routes[4].uri=lb://BedManagement
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/bedAssignment/**

# =========================
# Appointment Management
# =========================
spring.cloud.gateway.server.webflux.routes[5].id=AppointmentManagement
spring.cloud.gateway.server.webflux.routes[5].uri=lb://AppointmentManagement
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/appointment/**

# =========================
# Notification Service
# =========================
spring.cloud.gateway.server.webflux.routes[6].id=NotificationService
spring.cloud.gateway.server.webflux.routes[6].uri=lb://NotificationService
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/notifications/**
