spring.application.name=NotificationService

server.port=8003

# Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.instance-id=${spring.application.name}:${spring.instance.instance_id:${random.value}}

# SendGrid
sendgrid.api_key=${API_KEY}
sendgrid.from_email=burugukavya025@gmail.com
sendgrid.from_name=MedSync Notifications
